GET http://localhost:1337/cart-items
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNjM5OTk3NzU5LCJleHAiOjE2NDI1ODk3NTl9.xkDPMLrWF9VxObwRLDjXjYvMho-yunHCE6o0Z7O1yX8

###

POST http://localhost:3000/api/login
Content-Type: application/json

{
  "email": "alice@example.com",
  "password": "Alice123"
}

###

POST http://localhost:1337/auth/local 
Content-Type: application/json

{
  "identifier": "alice@example.com",
  "password": "Alice1231"
}

###

GET http://localhost:1337/users/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNjM5OTk3NzU5LCJleHAiOjE2NDI1ODk3NTl9.xkDPMLrWF9VxObwRLDjXjYvMho-yunHCE6o0Z7O1yX8

###

POST http://localhost:1337/auth/local/register
Content-Type: application/json

{
  "username": "Charlie",
  "email": "charlie@example.com",
  "password": "Carlie123"
}
